# Serverless Framework 

service: hydro-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.8

  region: us-east-1

  environment:
    DYNAMODB_TABLE: hydro_log
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ${file(./var/settings.yml):hydroTable} # Stored in an untracked file for security reasons

functions:
  create:
    handler: handlers/create.create
    events:
      - http:
          path: create
          method: post
          cors: true

  get:
    handler: handlers/get.get
    events:
      - http:
          path: get
          method: get
          cors: true